project:
  type: book

book:
  title: "SoilWood methodology paper"
  subtitle: "Methodological developments for measuring elemental concentrations with iTrax and LA-ICPMS"
  author: "Gregory van der Heijden"
  date: last-modified
  chapters:
    - index.qmd
    - part: "1. LA-ICPMS"
      chapters:
        - md/1_LA-ICPMS/0_LA-ICPMS.qmd
        - md/1_LA-ICPMS/1_LA-ICPMS_variability.qmd
    - part: "2. iTrax"
      chapters:
        - md/2_iTrax/0_iTrax.qmd
  
execute:
    warning: false
    message: false
    freeze: auto
    fig-width: 10
    fig-height: 8
    fig-dpi: 300
    fig.show: "hold"

format:
    html:
        toc: true
        toc-location: right
        toc-title: "Contents"
        code-fold: true
        theme: cosmo
        css: styles.css
        page-layout: article
        comments: 
          hypothesis: true
        number-sections: false
        # number-depth: 2
