project:
  type: book

book:
  title: "SoilWood methodology paper"
  subtitle: "Methodological developments for measuring elemental concentrations with iTrax and LA-ICPMS"
  author: "Gregory van der Heijden"
  date: last-modified
  chapters:
    - index.qmd
    - md/1_Material-Methods/0_Material_Methods.qmd
    - part: "LA-ICPMS"
      chapters:
        - md/2_LA-ICPMS/0_LA-ICPMS.qmd
        - text: "Inter-series Variability"
          file: md/2_LA-ICPMS/1_LA-ICPMS_variability.qmd
    - part: "iTrax"
      chapters:
        - md/3_iTrax/0_iTrax.qmd

  
execute:
    warning: false
    message: false
    freeze: auto
    fig-width: 10
    fig-height: 8
    fig-dpi: 300
    fig.show: "hold"

# crossref:
#   chapters: false

format:
    html:
        toc: true
        toc-location: right
        toc-title: "Contents"
        code-fold: true
        theme: cosmo
        css: styles.css
        page-layout: article
        comments: 
          hypothesis: true
        number-sections: true
        number-depth: 3
